### ISSUE TITLE
auto-accept on fingerprint check prior to ansible play

### ISSUE THREAD

**Issue by dchhouen** [PierreBeucher/cloudypad#16]
![finger-print-check](https://github.com/user-attachments/assets/166dd362-6cc7-496c-99e3-5da5fdadbb08)

a suggestion to skip host checking so user does not need to type in yes for fingerprint check during ansible playbook execution

ref - https://stackoverflow.com/questions/23074412/how-to-set-host-key-checking-false-in-ansible-inventory-file

**Comment by PierreBeucher** [comment]
Hi there, thanks for this suggestion ! Funny I actually implement this yesterday (https://github.com/PierreBeucher/cloudypad/pull/18/commits/15ee9780c1bf8bddfe49c3837a3c3e4497668ea4), will merge it soon :)

**Comment by PierreBeucher** [comment]
Should be good now with https://github.com/PierreBeucher/cloudypad/pull/18 :)
