### ISSUE TITLE
Use spot instances for cheaper instances

### ISSUE THREAD

**Issue by chocolatemoo53** [PierreBeucher/cloudypad#41]
Cloudypad should employ the use of spot instances. For reference, they are preemptable instances which utilize spare capacity. This can be seen as risky due to major/minor data loss by an on demand request from another user. However, for this downside they provide significant savings. You can use something like:

`
aws ec2 request-spot-instances --instance-count 1 --type "one-time"  
`

with the AWS CLI and request a singular one time spot instance and specify whatever other properties you'd like to launch it with. Maybe if someone is worried about data loss, they can simply select on demand through a prompt from cloudypad allowing the end user to use either option for more flexibility. 

Of course other providers offer spot instances but I am not directly familiar with their operations/CLIs.

**Comment by PierreBeucher** [comment]
Definitely a must have

**Comment by PierreBeucher** [comment]
I'm happy to announce it's ready with release 0.7.0 ! :partying_face: This will provide significant savings indeed. Update doc for Spot pricing as well.
