### ISSUE TITLE
Paperspace provision error

### ISSUE THREAD

**Issue by paintenzero** [PierreBeucher/cloudypad#42]
When I tried to provision a VM on Paperspace I got an error
```
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<CloudyPadAxiosError>".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

I don't know the origin of this error yet but then I tried to run cloudypad with `provision cloudy` args and I get:
```
Error provisioning instance cloudy: TypeError: Cannot read properties of undefined (reading 'skipAuthCheck')
    at PaperspaceProvisioner.provision (/cloudypad/dist/src/providers/paperspace/provisioner.js:33:19)
    at Command.<anonymous> (/cloudypad/dist/src/index.js:309:9)
```
Quick look at sources show that in index.ts:310 there are no opts passed.

**Comment by PierreBeucher** [comment]
Uh, probably missed a try-catch somewhere. The second error is expected as the initialization process failed mid-path, leaving an inconsistent state.

Can you please:
- Delete your instance with `cloudypad destroy cloudy`
- Try recreating with verbose, eg. `cloudypad create --verbose 0` to better identity where the error was thrown

**Comment by paintenzero** [comment]
Second error can be fixed by adding empty object like so `await p.provision({})`. I tried it and now I get the error from Paperspace that my account is not verified ;)

**Comment by PierreBeucher** [comment]
Ah right this would provide empty default option, but command would probably fail nonetheless. Thanks for feedback !

Indeed you may need to verify your account and increase quota with Paperspace before creating instances. I'll document that point.

**Comment by paintenzero** [comment]
Actually I debugged opts argument on your first call with _create_ command and you pass it empty as well. It is okay because state manager is the where you store all the parameters and opts is barely used in paperspace. Didn't look at another providers though.

**Comment by PierreBeucher** [comment]
Thanks for the info, it might be a bug indeed I'll take a look ;)

**Comment by PierreBeucher** [comment]
Please let me know if it finally worked for you with Paperspace

**Comment by paintenzero** [comment]
I am waiting for a response from them and Amazon. Will try them both once they approved quota increase

**Comment by PierreBeucher** [comment]
> Second error can be fixed by adding empty object like so await p.provision({}). I tried it and now I get the error from Paperspace that my account is not verified ;)

That was a bug indeed, good catch ! On interface `opts` it's optional: 

```
export interface InstanceProvisioner {
    provision(opts?: InstanceProvisionOptions): Promise<void>
```

But Paperspace implementation made it required, so `undefined` was passed to a function expecting something. 

```
export class PaperspaceProvisioner {
    async provision(opts: InstanceProvisionOptions) { ... }
```

I'm curious as to why TS compiler did not complain. Will try to add proper linting.

**Comment by PierreBeucher** [comment]
Should be fixed via https://github.com/PierreBeucher/cloudypad/pull/43
