### ISSUE TITLE
[new feature] Spot instances in GCP

### ISSUE THREAD

**Issue by JScaffo** [PierreBeucher/cloudypad#49]
Hi!

GCP allows for SPOT instances that run significantly cheaper than standard instances, with the downside that they can shut down if there are not enough resources available to other users that require a standard instance.

Setting the max run duration of the instance to 6hr I didnt have any problems running my spot instance and I think it would be beneficial to have the option as it can halve the costs.

It should be easy to add with pulumi gcp.compute.instance (https://www.pulumi.com/registry/packages/gcp/api-docs/compute/instance/), here are the important parameters:

![image](https://github.com/user-attachments/assets/cc790764-c415-47ad-a248-4d5e99d8f0bf)

![image](https://github.com/user-attachments/assets/413363c7-3e6c-4609-8a06-2cdef5cbe1f3)

Thank you and keep up the good work!

**Comment by PierreBeucher** [comment]
Hi there ! Thanks for your suggestion, I'm actually actively working on it via https://github.com/PierreBeucher/cloudypad/pull/43 - I hope to release by end of september. 

There's an issue already open for Spot: https://github.com/PierreBeucher/cloudypad/issues/41 so I'm gonna close this one, feel free to comment on the other issue ;)

**Comment by PierreBeucher** [comment]
Working on it via https://github.com/PierreBeucher/cloudypad/pull/43, hoping to release by end of september
