### ISSUE TITLE
Failed to create a new AWS instance

### ISSUE THREAD

**Issue by mikaelmorvan** [PierreBeucher/cloudypad#50]
[cloudypad output.txt](https://github.com/user-attachments/files/16922521/cloudypad.output.txt)

I want to create a new instance of CloudyPad on AWS
I launch cloudypad create and I've got a problem with the installation of the nvidia driver

The output of the command is in the attached file

Hope it will help

**Comment by PierreBeucher** [comment]
Hey Mikael, I solved this bug yesterday via https://github.com/PierreBeucher/cloudypad/pull/46 (see https://github.com/PierreBeucher/cloudypad/issues/44), can you update to latest version and try again ? (just run installation script again it will update Cloudy Pad)

**Comment by mikaelmorvan** [comment]
The update doesn't work
`
curl -fsSL https://raw.githubusercontent.com/PierreBeucher/cloudypad/master/install.sh | sh
Installing Cloudy Pad version v0.6.0
Installation aborted.
`

**Comment by mikaelmorvan** [comment]
I had to download the install.sh manually, chmod +x it, and launch it to be able to update the install of Cloudypad

**Comment by mikaelmorvan** [comment]
Everything is working smoothly with the new aws installation
Great Job Pierre

**Comment by PierreBeucher** [comment]
Reproduced and solved with https://github.com/PierreBeucher/cloudypad/pull/51 :) Thanks for the feedback !
