### ISSUE TITLE
Steam initial setup get stuck on network selection

### ISSUE THREAD

**Issue by PierreBeucher** [PierreBeucher/cloudypad#52]
## Bug 

For fresh installation, Steam in Big Picture mode may get stuck on the Network selection page. When selecting the network, it shows a page with yellow text and goes back immediately to the network selection page.

This bug is probably not related to Cloudy Pad but some underlying component (maybe the Steam Docker image or Steam itself) and may appear on previously stable Cloudy Pad releases. We're enquiring the issue.

See also:

- [Wolf issue](https://github.com/games-on-whales/wolf/issues/120)
- [Wolf Discord thread](https://discord.com/channels/856434175455133727/1284532285655220245)

## Workaround

SSH into your Cloudy Pad instance:

```sh
ssh ubuntu@<IP>
```

Open Wolf config as root:
 
```sh
sudo nano /etc/wolf/cfg/config.toml
```

Update Steam `[[app]]` config to add/update environment variable:

```
# Keep existing variables and add
env = [ ... , "STEAM_STARTUP_FLAGS=-steamos3" ]
```

Alternatively copy file locally for edit and copy it back

```sh
scp ubuntu@<IP>:/etc/wolf/cfg/config.toml wolf-config.toml
```

Restart Wolf:

```
docker restart wolf
```

Connect with Moonlight, Steam should start in "classic" mode and you'll be able to connect.

You can then keep Steam this way or update back to Big Picture mode which should connect without issue.

**Comment by JScaffo** [comment]
Found this issue today, thank you for the workaround!

**Comment by PierreBeucher** [comment]
This should mostly be fixed by https://github.com/games-on-whales/gow/commit/ba0bc43faa019daeb146fac759e7a5a9d351ecd5 - disabling Big Picture altogether.

**Comment by PierreBeucher** [comment]
This bug seems to have disappeared. Closing now.
