### ISSUE TITLE
dockerfile error

### ISSUE THREAD

**Issue by sjoerdje-c** [PierreBeucher/cloudypad#59]
Hi! thanks for this project, I'm going through your process to setup an instance and after issuing the command `cloudypad create` it returns this error.

![Capture](https://github.com/user-attachments/assets/f997cfae-a0bf-4e35-a96f-729de268284b)

**Comment by sjoerdje-c** [comment]
apparently, confirming my email address for the docker desktop account set up fixes this issue.

carry-on!

**Comment by PierreBeucher** [comment]
Hi there, glad you worked around your issue ! Were you able to setup your instance ? By the way, did you bump into https://github.com/PierreBeucher/cloudypad/issues/52 ?

**Comment by sjoerdje-c** [comment]
Hi Pierre,

No, not yet. I'm waiting for a quota increase approval (from 0 to 1) on Google Cloud.

I haven't bumped into issue 52. Yet!

Thanks!
________________________________
